# Generated by Django 5.2.7 on 2025-11-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
