# Generated by Django 5.2.7 on 2025-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regTrib',
            field=models.CharField(default='01', max_length=2),
        ),
    ]
